services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: media_share_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "media_share_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start:dev"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/media_share_db
      ADMIN_PASSWORD: admin123
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm start"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pg_data:
