version: "3.8"
services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: media_share_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  nestjs:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/media_share_db
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./uploads:/app/uploads

volumes:
  pg_data: