#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function writeJson(file, json) {
  fs.writeFileSync(file, JSON.stringify(json, null, 2) + '\n', 'utf8');
}

function bumpVersion(version) {
  const [major, minor, patch] = version.split('.').map(Number);
  return [major, minor, (patch || 0) + 1].join('.');
}

function main() {
  const pkgPath = path.resolve(__dirname, '..', 'package.json');
  const versionFilePath = path.resolve(__dirname, '..', 'src', 'version.ts');

  const pkg = readJson(pkgPath);
  const newVersion = bumpVersion(pkg.version || '0.0.0');
  pkg.version = newVersion;
  writeJson(pkgPath, pkg);

  const versionFileContent = `// This file is auto-generated by scripts/bump-version.js\n// Do not edit manually\nexport const APP_VERSION = \"${newVersion}\";\n`;
  fs.writeFileSync(versionFilePath, versionFileContent, 'utf8');
  console.log('Bumped version to', newVersion);
}

main();


